[package]
name = "sylvanite"
version = "1.1.0"
edition = "2021"
authors = ["Franklin Delehelle <delehelle@ens.fr>"]
license = "CECILL-2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
atty = "0.2"
clap = { version = "3", features = ["derive"] }
indicatif = {version = "0.16", features = ["rayon"]}
itertools = "0.10"
log = "0.4"
newick = "0.5"
ordered-float = "2"
rayon = "1.5"
rusqlite = "0.26"
stderrlog = "0.4"

[package.metadata.release]
tag-prefix = ""
publish = false
pre-release-hook = ["git-cliff", "-o", "CHANGELOG.md", "--tag", "{{version}}"]
allow-branch = ["master"]
