[package]
name = "sylvanite"
version = "0.1.0"
edition = "2021"
authors = ["Franklin Delehelle <delehelle@ens.fr>"]
license = "CECILL-2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3", features = ["derive"] }
rayon = "1.5"
anyhow = "1"
rusqlite = "0.27"
newick = { path = "../newick" }
indicatif = {version = "0.16", features = ["rayon"]}
atty = "0.2"
log = "0.4"
stderrlog = "0.5"
